# Generated by Django 2.2.1 on 2019-12-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('t', models.IntegerField(blank=True, default=0, null=True)),
                ('y', models.IntegerField(blank=True, default=0, null=True)),
                ('n', models.IntegerField(blank=True, default=0, null=True)),
                ('m', models.IntegerField(blank=True, default=0, null=True)),
                ('u', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('win_date', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('new', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('joined_on', models.DateField()),
                ('nurse', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1)),
                ('position', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('new', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='nursesApp.Contributor')),
            ],
        ),
    ]
